/**
 * Pixel-portrait bitmaps, extracted 1:1 from 集合/hero肖像/頭.png.
 *
 * PORTRAIT_FACE (head + glasses + body, 48x47) and PORTRAIT_HELLO — a bold
 * uppercase "HELLO" wordmark (9x40), positioned and scaled independently in
 * the hero layout to sit large and heavy to the right of the portrait.
 */
export const PORTRAIT_FACE: string[] = [
  ".................XXXXXXXX......................",
  "...............XXXXXXXXXXXXXXXX................",
  "............XXXXXXXXXXXXXXXXXXX................",
  "..........XXXXXXXXXXXXXXXXXXXXXX...............",
  ".........XXXXXXXXXXXXXXXXXXXXXXXX..............",
  "........XXXXXXXXXXXXXXXXXXXXXXXXX..............",
  ".......XXXXXXXXXXXXXXXXXXXXXXXXXXXX............",
  "......XXXXXXXXX..XXXXXXXXXXXXXX.XXXX...........",
  "......XXXXXXX.....XXXXXXXXXXXX..XXXXX..........",
  "......XXXXXX...............X..XXXXXXX..........",
  "......XXXXX................X.XXXXXXXXX.........",
  ".....XXXXXX.................XXXXXXXXXX.........",
  "....XXXXXXXX................XXXXXXXXXX.........",
  "....XXXXXXXX.................XXXXXXXXXX........",
  ".....XXXXXX..................XXXXXXXXXX........",
  ".....XXXXXX....................XXXXXXXX........",
  ".....XXXXX...XXXX......XXX.....XXXXXXXX........",
  "......XXXX.....................XXXXXXXX........",
  "......XXXX.XXXXX.......XXXX.....XXXXXXX........",
  "........XXX....XX.....X....XX..XXXXXXX.........",
  "........XX......XX...X......XX.XXXXXXX.........",
  "............XXX..XXXXX..XX...XXXX..XXX.........",
  "........X...XXX..X..XX..XX...XXXX...X..........",
  ".......X....XX...X...X..X....X.X.X..X..........",
  ".......X.X......X....X.......X......X..........",
  ".......XXX.....XX.....X.....X....X..X..........",
  ".........X.XXXXX.X.....XXXXX.......X...........",
  ".........X.......X.................X...........",
  ".........X.......XX.............XXX............",
  ".........X........XX............XX.............",
  ".........X......................X..............",
  "..........X.............X......XX..............",
  "..........X.....X......X.......X...............",
  "...........X.....XXXXXX.......XX...............",
  "............X..............X...X...............",
  ".............X............X....X...............",
  "..............X................XX..............",
  "..............X..........X.....XXX.............",
  ".............XXX........X.....XXXXX............",
  "............XXXXXXXXXXXX.....XXXX.XXX..........",
  "...........XX.XXX...........XXXXX.XXXXX........",
  "........XXXXX.XXX..........XXXXX.XXXXXXXXX.....",
  "......XXXXXXX..XXX.......XXXXXX..XXXXXXXXXXX...",
  "....XXXXXXXXX...XX.......XXXXX..XXXXXXXXXXXXX..",
  "..XXXXXXXXXX.....X......X.XXX..XXXXXXXXXXXXXX..",
  "..XXXXXXXXXX..XXXX....XXXX....XXXXXXXXXXXXXXX..",
  ".XXXXXXXXXXX.XXXXX...XXXXXX..XXXXXXXXXXXXXXXXX.",
  "XXXXXXXXXXXXXXXXXX..XXXXXXX..XXXXXXXXXXXXXXXXXX",
];

export const PORTRAIT_HELLO: string[] = [
  "XX...XX..XXXXXX..XX......XX.......XXXXX.",
  "XX...XX..XXXXXX..XX......XX......XXXXXXX",
  "XX...XX..XX......XX......XX......XX...XX",
  "XXXXXXX..XXXXX...XX......XX......XX...XX",
  "XXXXXXX..XXXXX...XX......XX......XX...XX",
  "XX...XX..XX......XX......XX......XX...XX",
  "XX...XX..XX......XX......XX......XX...XX",
  "XX...XX..XXXXXX..XXXXXX..XXXXXX..XXXXXXX",
  "XX...XX..XXXXXX..XXXXXX..XXXXXX...XXXXX.",
];
